name = "Gpiod"
uuid = "fc5cb0c8-de5a-498d-9e5a-0d5c8fd467e9"
authors = ["Alexander Barth"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
